repos: []
# repos:
# - repo: local
#   hooks:
#     - id: pylint
#       name: pylint
#       entry: python -m pylint UD1_Python
#       language: system
#       pass_filenames: false
#     - id: pytest
#       name: pytest
#       entry: python -m pytest UD1_Python/Ejercicios/tests
#       language: system
#       pass_filenames: false
