name: CI for UD1_Practica_Vigenere

on:
  push:
#    branches: [ main ]
  pull_request:
#    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PRACTICA: UD1_Python/Practica_Vigenere  # ajusta según práctica
      CENTRAL_REPO: 25_26-ADAT-UDA

    steps:
      # 1. Checkout del repo actual (alumno o tuyo)
      - name: Checkout current repo
        uses: actions/checkout@v4

      # 2. Instalar Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Si estamos en el repo del alumno: bajar tests desde tu repo central
      - name: Download official tests (only if not central repo)
        if: github.repository != 'ADAT-2526-CJ/25_26-ADAT-UDA'
        run: |
          echo "Descargando tests oficiales de $PRACTICA..."
          git clone --depth 1 --filter=blob:none --sparse https://github.com/ADAT-2526-CJ/25_26-ADAT-UDA tmp_tests
          cd tmp_tests
          git sparse-checkout set $PRACTICA/tests
          cd ..
          mkdir -p tests
          cp -r tmp_tests/$PRACTICA/tests/* ./tests/

      - name: Debug repo contents
        run: |
          pwd
          ls -R
          
      # 4. Instalar dependencias si hay
      - name: Install dependencies from practice
        run: |
          if [ -f $PRACTICA/requirements.txt ]; then
            pip install -r $PRACTICA/requirements.txt
          else
            echo "No requirements.txt found for $PRACTICA"
          fi

      # 5. Ejecutar el linter para comprobar estilo y buenas prácticas
      - name: Run pylint
        run: python -m pylint $PRACTICA/src



      # 6. Ejecutar los tests oficiales con detalle (-v) y mostrando prints (-s)
      - name: Run tests
        run: PYTHONPATH=. python -m pytest $PRACTICA/tests/ -v -s

